remote_theme: cotes2020/jekyll-theme-chirpy

title: SPACESHIP EARTH v2.0
tagline: You Are Crew
description: >-
  Systems failing while technology advances. That's not you failing to understand.
  That's you correctly perceiving artificial scarcity architecture.

url: "https://noahobodhi.github.io"
baseurl: "/SSE2-Public"

github:
  username: NoahOBodhi

social:
  name: Noah O. Bodhi
  email: noah.o.bodhi@proton.me
  links:
    - https://github.com/NoahOBodhi

theme_mode: light

avatar: 

toc: true

comments:
  active: false

paginate: 10

timezone: America/New_York

google_analytics:
  id: 

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed